#!/usr/bin/env python3
import os
import sys

if len(sys.argv) > 2:
	print("no argv!")
	sys.exit(1)

s:str = sys.argv[1]

def search(current_path='.'):
	f = os.listdir(current_path)

	for i in f:

		fullpath = os.path.join(current_path,i)

		if os.path.isfile(fullpath):
			if i == s:
				print("file is - ",current_path)
				return True
		elif os.path.isdir(fullpath):
			if search(fullpath):
				return True
	return False


if __name__ == "__main__":
	if not search():
		print("file not found!")